version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    networks: 
      - unlogged_network
    environment:
      MYSQL_DATABASE: unlogged_demo
      MYSQL_ROOT_PASSWORD: root_password


  demo-app:
    container_name: target-repo
    build:
      context: ../
    volumes:
      - /Users/kt/.unlogged/:/root/.unlogged/
      - /Users/kt/.m2/repository/video/bug/unlogged-sdk:/root/.m2/repository/video/bug/unlogged-sdk
    ports:
      - "8080:8080"
      - "12100:12100"
    depends_on:
      - mysql
    networks: 
      - unlogged_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/unlogged_demo
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: 'true'
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
      userpassword: "oMIYSqNZMrH5iun"

networks:
  unlogged_network:
    driver: bridge 
